### ISSUE TITLE
npm package please :)

### ISSUE THREAD

**Issue by bonesoul** [LeoColomb/flag-sprites#5]

**Comment by LeoColomb** [comment]
Well, I don't think this is a good idea, I must instead consider archiving this repo.

You may prefer to use more modern way to show flags (using SVG, using a more optimized process, etc.), since three year, there is a room of improvements to match current web environnement.
I even not sure all flags are still up-to-date.

As I don't want to publish outdated piece of code, I will decline your request. Sorry!

That said, if you want to update this repo code, feel free to create a PR! 😺
